/**
 * Method to set/insert/update a class after validation
 * @param {object} Clas object to save
 * @param {Function} dbMethod method used to save the clas object into DB
 * @return {promise} Returns promise generated by the dbMethod call
 */
module.exports = async function validateAndSetClass(clas, dbMethod) {
  const isSafeHtml = require("../../validations/isSafeHTML");

  if (!isSafeHtml(clas.description))
    throw new Error("Class description is not a sanitized HTML.");

  return dbMethod(clas);
};
