const bookings = [
  {
    id: 200,
    name: "Takenoko no sato",
    email: "take@gmail.com",
    className: "Advanced Guitar",
    startTime: "09:00",
    classID: 2,
  },
  {
    id: 122,
    name: "Honey Butter Chips",
    email: "hbc@gmail.com",
    className: "Advanced Guitar",
    startTime: "09:00",
    classID: 2,
  },
  {
    id: 434,
    name: "Yanyan",
    email: "yan@gmail.com",
    className: "Advanced Guitar",
    startTime: "09:00",
    classID: 2,
  },
  {
    id: 939,
    name: "Pocky",
    email: "pocky@gmail.com",
    className: "Advanced Guitar",
    startTime: "09:00",
    classID: 2,
  },
  {
    id: 102,
    name: "Genki Sushi",
    email: "genki@gmail.com",
    className: "Basic Guitar",
    startTime: "13:00",
    classID: 0,
  },
  {
    id: 149,
    name: "Koi",
    email: "koi@gmail.com",
    className: "Basic Guitar",
    startTime: "13:00",
    classID: 0,
  },
  {
    id: 687,
    name: "Haribo",
    email: "haribo@gmail.com",
    className: "Basic Guitar",
    startTime: "13:00",
    classID: 0,
  },
  {
    id: 157,
    name: "Hello Panda",
    email: "hp@gmail.com",
    className: "Basic Guitar",
    startTime: "13:00",
    classID: 0,
  },
  {
    id: 976,
    name: "Green Tea Latte",
    email: "green@gmail.com",
    className: "Basic Guitar",
    startTime: "13:00",
    classID: 0,
  },
];

module.exports = { bookings };
