// https://www.dbml.org/docs/

// Legend:
// PG (Attribute) -> PostgreSQL (preferred DB choice)
// FS (Attribute) -> Firestore (preferred DB choice)
// Trimmable (Attribute) -> Data that can be warehoused by deleting older data from production after backing up everything into data warehouse

Project ClassExpress {
  database_type: 'PostgreSQL'
  Note: 'SQL DB for Class Express'
}

// FS
Table userAccounts {
  id int [pk, increment, not null]
  createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  email varchar [not null, unique]
  phoneNumber varchar [null] // Includes area code
  firstName varchar [not null]
  lastName varchar [null]
  countryCode varchar [not null]
  cityCode varchar [not null] // @todo Should this allow null? If null, then use country
  timezone varchar [not null]
  profilePictureURL varchar [null]
  currency varchar [not null]
  verified_email boolean [default: false]
  verified_phone boolean [default: false]
  deleted boolean [default: false]
}

// FS
Table userSettings {
  id int [pk, not null, ref: - userAccounts.id]
  notification_email boolean [null]
  notification_mobile boolean [null]
  // @todo Add a updatedAt timestamp
}

// FS
// Partners / Business organisations.
Table partners {
  id int [pk, increment, not null]
  createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  name varchar [not null]
  description varchar [not null]
  email varchar [not null]
  phoneNumber varchar [not null] // Includes area code
  location_address varchar [not null]
  location_coordinates varchar [not null]
  website varchar [null]
  pictureSources varchar // Perhaps use an array?
  verified_email boolean [default: false]
  verified_phone boolean [default: false]
  verified boolean [default: false] // Is the business verified by us (Class Express)?
  // billingAccount int [not null] // Foreign key to billing accounts?
  deleted boolean [default: false]
}

// FS
// Individual users (employees) of a Partner / Business organisation
Table partnerAccounts {
  id int [pk, increment, not null]
  createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  partners int [ref: > partners.id, not null]
  name varchar [not null]
  admin boolean [not null] // True if user is admin else is employee
  permissions varchar // Perhaps use an array?
  email varchar [not null]
  phoneNumber varchar [null] // Includes area code
  verified_email boolean [default: false]
  verified_phone boolean [default: false]
  deleted boolean [default: false]
}

// FS
Table partnerSettings {
  id int [pk, ref: - partnerAccounts.id, not null]
  notification_email boolean [null]
  notification_mobile boolean [null]
  // @todo Add a updatedAt timestamp
}

// @todo Create 1 more table for records of points purchase for calculating user points
// @todo Might wanna put these records in userPlans instead so that they are all in 1 table and can be merged easily

// Trimmable + PG
// Since planID is fixed and does not change overtime, we can use it to get cost of plan and currency used
Table userPlans {
  id int [pk, increment, not null]
  // @todo Either createAt or updatedAt to track when this is updated for analytics purposes
  // createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  userID int [ref: > userAccounts.id, not null] // Many rows with each row being 1 plan in users history
  planID int [ref: > subscriptionPlans.id, not null]
  // Might look into using ISO 8061 defaults, but using unix seconds for now for consistency
  start bigint [not null]
  end bigint [null]
}

// Trimmable + PG
// Instead of relying on a Points table that needs to be updated every month, perhaps use a transactions table and the userPlans table to compute the points on demand
// Bascially records of user bookings and cancellation events and more
// Closely tied to userClasses
// @todo Do we need to add the start time of the class?
Table userBookingTransactions {
  id int [pk, increment, not null]
  actionTime bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`] // TS should be provided by client, but defaults to server timestamp if none
  userID int [ref: > userAccounts.id, not null]
  classID int [ref: > classes.id, not null]
  points int [not null] // A copy of the points of the class at the moment of action
  // Both booked and cancelled defaults to false to make it easier as only need to set one to be true on insert
  booked boolean [default: false]
  cancelled boolean [default: false]
}

// @todo Create 1 more table for userBillingTransactions
// @todo Create the other tables for billing transactions too.

// @todo
Table billingAccounts {
  id int [pk, increment, not null]
  createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  // @todo Verified? Verification probably by stripe or something?
  // @todo ?? deleted boolean [default: false]
}

// FS or PG
Table classes {
  id int [pk, increment, not null]
  createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  partnerID int [ref: > partners.id, not null]
  name varchar [not null]
  description varchar [not null] // HTML allowed
  length int [not null]
  points int [not null]
  maxParticipants int [not null]
  pictureSources varchar [null] // Perhaps use an array?
  location_address varchar [null]
  location_coordinates varchar [null]
  deleted boolean [default: false]
}

// FS or PG
// Each row will be a individual RRULE?
// @todo
Table classSchedule {
  id int [pk, increment, not null]
  classID int [ref: > classes.id, not null]
  // @todo Either createAt or updatedAt to track when this is updated for analytics purposes
  // createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
}

// PG or FS
Table userFavourites {
  id int [pk, increment, not null]
  userID int [ref: > userAccounts.id, not null]
  favouritedAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`] // TS should be provided by client, but defaults to server timestamp if none
  // Only one will be nulled, either classID or partnerID
  // Get classIDs by filtering for NOT NULL classIDs
  classID int [ref: > classes.id, null] // Defaults to null
  // Get partnerIDs by filtering for NOT NULL partnerIDs
  partnerID int [ref: > partners.id, null] // Defaults to null
}


// @todo Do we actually need this? Or can this be generated from userBookingTransactions table?
// PG or FS + Trimmable (keep like the latest 20 user past classes, allow user to request for more)
// Classes that the user have booked/attended/booked+cancelled(by user or partner)
Table userClasses {
  id int [pk, increment, not null]
  userID int [ref: > userAccounts.id, not null]
  classID int [ref: > classes.id, not null]
  // Only store start time as end time should be computed using length of class
  // Might look into using ISO 8061 defaults, but using unix seconds for now for consistency
  startTime bigint [not null]
}

// All subscription plans across time
Table subscriptionPlans {
  id int [pk, increment, not null] // This is also the planID
  createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  available boolean [default: true] // By default all plans are available // @todo Can change to be a procedure to be executed to see if this is avail?
  name varchar [not null]
  copywriting varchar [not null] // HTML allowed
  currency varchar [not null]
  price int [not null] // Price in the specified currency
  totalPoints int [not null]
  // Country that this plan is available in = All countries if none specified
  // Usually need to specify and usually the same as the currency of the plan.
  // @todo Defaults to SG?
  // Multiple rows, 1 row for each unique countryCode
  countryCode varchar [null]
}

// FS
// All topupOptions allowed other then the custom points topup
Table topupOptions {
  id int [pk, increment, not null]
  createdAt bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  available boolean [default: true] // By default all plans are available // @todo Can change to be a procedure to be executed to see if this is avail?
  name varchar [not null]
  copywriting varchar [not null] // HTML allowed
  currency varchar [not null]
  price int [not null]
  totalPoints int [not null]
}

// PG + Trimmable (If trimmed, we need to make this into a seperate service that will hold a materialized view with cached result)
// PG needed for advance processing, to add a caching layer in front of queries for this with a 1 ~ 2 days expiry?
Table reviews {
  id int [pk, increment, not null]
  reviewedOn bigint [default: `EXTRACT(EPOCH FROM now() at time zone 'utc')`]
  classID int [ref: > classes.id, not null]
  // @todo Add what time was the lesson so partner can take action
  points int [not null]
  description varchar [null]
}
